# This workflow is triggered every time a change is pushed to any branches 
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On Code Change (PR)

# The workflow could also be triggered on PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      - /feature-.*/
      - /[0-9]_[0-9]_x/
      - /[0-9]_x/

jobs:
  update-signature:
    name: Update module signature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jahia/jahia-modules-action/update-signature@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_enterprise_releases_url: ${{ secrets.NEXUS_ENTERPRISE_RELEASES_URL }}

  build:
    name: Build Module
    needs: update-signature
    runs-on: ubuntu-latest
    env:
      NEXUS_INTERNAL_URL: https://devtools.jahia.com/nexus/content/groups/internal/
    container:
      image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: jahia/jahia-modules-action/build@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          module_id: ldap
          mvn_settings_filepath: '.github/maven.settings.xml'

  sonar-analysis:
    name: Sonar Analysis
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jahia/jahia-modules-action/sonar-analysis@v2
        with:
          primary_release_branch: master
          github_pr_id: ${{github.event.number}}
          sonar_url: ${{ secrets.SONAR_URL }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          mvn_settings_filepath: '.github/maven.settings.xml'